#!/usr/bin/env bash
# Onboard a new tool: allocates a port, writes config.env, regenerates nginx conf,
# adds the tool to the services page (site-src/data/services.json) and rebuilds the site.
# Does NOT commit or sync — run git add/commit and sync-to-amunet.sh after reviewing.
#
# Usage:  ./scripts/onboard-tool.sh <user> <tool>
# Example: ./scripts/onboard-tool.sh sky_max instagram-stats

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TOOLS_DIR="$REPO_ROOT/amunet/tools"

if [[ $# -ne 2 ]]; then
    echo "Usage: $0 <user> <tool>" >&2
    echo "Example: $0 sky_max instagram-stats" >&2
    exit 2
fi

USER_NAME="$1"
TOOL_NAME="$2"

NAME_RE='^[a-z_][a-z0-9_-]*$'
if [[ ! "$USER_NAME" =~ $NAME_RE ]]; then
    echo "Error: invalid user name '$USER_NAME' (must match $NAME_RE)" >&2
    exit 1
fi
if [[ ! "$TOOL_NAME" =~ $NAME_RE ]]; then
    echo "Error: invalid tool name '$TOOL_NAME' (must match $NAME_RE)" >&2
    exit 1
fi

TOOL_DIR="$TOOLS_DIR/$USER_NAME/$TOOL_NAME"
if [[ -d "$TOOL_DIR" ]]; then
    echo "Error: $USER_NAME/$TOOL_NAME already onboarded" >&2
    echo "Existing config: $TOOL_DIR/config.env" >&2
    exit 1
fi

# Allocate the next free port in 8001-8099
NEXT_PORT=8001
if [[ -d "$TOOLS_DIR" ]]; then
    while IFS= read -r existing_port; do
        if (( existing_port >= NEXT_PORT )); then
            NEXT_PORT=$((existing_port + 1))
        fi
    done < <(find "$TOOLS_DIR" -name 'config.env' -exec grep -h '^INTERNAL_PORT=' {} \; 2>/dev/null | cut -d= -f2 | sort -n)
fi

if (( NEXT_PORT > 8099 )); then
    echo "Error: port range 8001-8099 exhausted" >&2
    exit 1
fi

mkdir -p "$TOOL_DIR"
cat > "$TOOL_DIR/config.env" <<CONFIG
# Auto-generated by scripts/onboard-tool.sh
# Do not edit by hand.
USER=$USER_NAME
TOOL=$TOOL_NAME
INTERNAL_PORT=$NEXT_PORT
ONBOARDED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
CONFIG

echo "✓ Allocated port $NEXT_PORT for $USER_NAME/$TOOL_NAME"
echo "✓ Created $TOOL_DIR/config.env"

"$REPO_ROOT/scripts/regenerate-nginx-conf.sh"

# Services page (http://amunet.tail49d1b.ts.net/sluzby/) — add the tool and rebuild.
SITE_OK=0
if command -v bun >/dev/null 2>&1 && [[ -d "$REPO_ROOT/site-src/node_modules" ]]; then
    ( cd "$REPO_ROOT/site-src" && bun run add-service.ts "$USER_NAME" "$TOOL_NAME" && bun run build.ts >/dev/null ) \
        && SITE_OK=1 && echo "✓ Rebuilt site (amunet/site/)"
fi
if (( ! SITE_OK )); then
    echo "" >&2
    echo "⚠ Services page NOT updated (bun or site-src/node_modules missing). Do it by hand:" >&2
    echo "    cd \"$REPO_ROOT/site-src\" && bun install && bun run add-service.ts $USER_NAME $TOOL_NAME && bun run build" >&2
fi

echo ""
echo "Next steps:"
echo "  1. Give it a real name + description:  site-src/data/services.json  (search \"/$USER_NAME/$TOOL_NAME/\")"
echo "     then:  (cd \"$REPO_ROOT/site-src\" && bun run build)"
echo "  2. git -C \"$REPO_ROOT\" add amunet/ site-src/data/services.json && git -C \"$REPO_ROOT\" commit -m 'Onboard $USER_NAME/$TOOL_NAME'"
echo "  3. \"$REPO_ROOT/scripts/sync-to-amunet.sh\""
echo ""
echo "Tool URL (once deployed): http://amunet.tail49d1b.ts.net/$USER_NAME/$TOOL_NAME/"
