#!/usr/bin/env bash
# Rebuild amunet/nginx/http.amunet-rogan.conf from all tools/*/*/config.env files.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TOOLS_DIR="$REPO_ROOT/amunet/tools"
TEMPLATE="$REPO_ROOT/templates/nginx-location.template"
OUTPUT="$REPO_ROOT/amunet/nginx/http.amunet-rogan.conf"

mkdir -p "$(dirname "$OUTPUT")"

{
    cat <<'HEADER'
# Auto-generated by amunet-rogan/infra — scripts/regenerate-nginx-conf.sh
# DO NOT EDIT BY HAND. Source of truth: github.com/amunet-rogan/infra

server {
    listen 80;
    listen [::]:80;
    server_name amunet.tail49d1b.ts.net;

    # Web Amunetu — staticke self-contained stranky, zdroj: site-src/ v tomhle repu.
    #   /              rozcestnik
    #   /sluzby/       seznam sluzeb
    #   /pro-martina/  prirucka
    # "^~" prefixy maji prednost pred regexy, takze je catchall nastroju nize
    # nespolkne. absolute_redirect off drzi presmerovani relativni, aby fungovalo
    # pres http i pres https (tailscale serve :443 -> :80).
    root /volume1/docker/amunet-rogan/site;
    absolute_redirect off;

    location = / {
        try_files /index.html =404;
        add_header Cache-Control "no-cache";
    }

    location = /sluzby      { return 301 /sluzby/; }
    location ^~ /sluzby/ {
        try_files $uri $uri/index.html =404;
        add_header Cache-Control "no-cache";
    }

    location = /pro-martina { return 301 /pro-martina/; }
    location ^~ /pro-martina/ {
        try_files $uri $uri/index.html =404;
        add_header Cache-Control "no-cache";
    }

    location = /favicon.ico {
        return 204;
        access_log off;
    }

HEADER

    if [[ -d "$TOOLS_DIR" ]]; then
        while IFS= read -r config; do
            user_v=$(grep '^USER=' "$config" | cut -d= -f2)
            tool_v=$(grep '^TOOL=' "$config" | cut -d= -f2)
            port_v=$(grep '^INTERNAL_PORT=' "$config" | cut -d= -f2)
            sed \
                -e "s|{USER}|$user_v|g" \
                -e "s|{TOOL}|$tool_v|g" \
                -e "s|{INTERNAL_PORT}|$port_v|g" \
                "$TEMPLATE"
            echo ""
        done < <(find "$TOOLS_DIR" -name 'config.env' 2>/dev/null | sort)
    fi

    cat <<'FOOTER'
    # Catchall for unknown tools — returns 404 instead of falling through to DSM
    location ~ ^/[^/]+/[^/]+/ {
        return 404 "Tool not found. Contact Jenda to onboard.\n";
    }
}
FOOTER
} > "$OUTPUT"

echo "✓ Wrote $OUTPUT"
